import { Auth } from './auth.js';

function esc(value) { return String(value == null ? '' : value).replace(/[&<>"']/g, function (c) { return ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]; }); }
function n(value) { return Math.max(0, Number(value) || 0); }
function pct(value) { return Math.max(0, Math.min(100, Math.round(n(value)))); }
function time(value) { value = Math.round(n(value)); if (value < 60) return value ? '<1m' : '0m'; var h = Math.floor(value / 3600), m = Math.round(value % 3600 / 60); return h ? h + 'h ' + m + 'm' : m + 'm'; }
function initials(value) { return String(value || '?').trim().split(/\s+|@/).map(function (part) { return part.charAt(0); }).join('').slice(0, 2).toUpperCase(); }
function rootUrl(path) { return new URL(path, new URL('../', import.meta.url)).href; }
function profileName(person) { return (person && (person.display_name || person.name || person.email)) || 'Student'; }
function roleName(role) { return role === 'admin' ? 'Administrator' : role === 'professor' ? 'Professor' : 'Student'; }

export function createAccountUI(options) {
  var modal = options.modal, closeModal = options.closeModal, header;
  function account() { return Auth.getAccount(); }
  function error(message) { return '<p class="account-error">' + esc(message || 'Something went wrong.') + '</p>'; }
  function dashboardUrl() { return rootUrl(account() && account().role === 'admin' ? 'control/' : 'dashboard/'); }
  async function signOut() { await Auth.signOut(); closeModal(); location.assign(rootUrl('signin/')); }

  function syncHeader() {
    if (!header) return;
    var a = account(); header.hidden = !a;
    if (!a) return;
    header.innerHTML = '<span class="account-avatar">' + initials(a.user.name || a.user.email) + '</span><span class="account-header-label">' + esc((a.user.name || a.user.email).split(' ')[0]) + '</span>';
    header.setAttribute('aria-label', 'Open account menu for ' + a.user.email);
  }
  function openSettings() {
    var a = account(); if (!a) return;
    var m = modal('<div class="control-eyebrow">Account settings</div><h2>Your profile</h2><p class="modal-sub">Your name appears in authorized teaching and administrator workspaces.</p><form class="account-form" id="profile-form"><label>Display name<input name="display_name" maxlength="80" value="' + esc(a.user.name || '') + '" placeholder="Your name"></label><label>Email address<input value="' + esc(a.user.email) + '" disabled></label><div id="profile-error"></div><div class="modal-actions"><button class="btn subtle" type="button" data-close>Cancel</button><button class="btn primary" type="submit">Save settings</button></div></form>');
    m.querySelector('#profile-form').onsubmit = async function (event) {
      event.preventDefault(); var form = event.currentTarget;
      try { await Auth.api('/api/account/me', { method: 'PATCH', body: JSON.stringify({ display_name: new FormData(form).get('display_name') }) }); await Auth.init(); syncHeader(); closeModal(); }
      catch (reason) { m.querySelector('#profile-error').innerHTML = error(reason.message); }
    };
  }
  function openAccount() {
    var a = account(); if (!a) return;
    var m = modal('<div class="account-menu-head"><span class="account-avatar large">' + initials(a.user.name || a.user.email) + '</span><div><strong>' + esc(a.user.name || a.user.email) + '</strong><p>' + esc(a.user.email) + '</p></div></div><span class="role-pill">' + esc(roleName(a.role)) + '</span><div class="account-menu-actions"><button class="btn primary" id="account-dashboard">Dashboard</button><button class="btn ghost" id="account-settings">Settings</button><button class="btn danger" id="account-logout">Sign out</button></div>');
    m.querySelector('#account-dashboard').onclick = function () { location.assign(dashboardUrl()); };
    m.querySelector('#account-settings').onclick = openSettings;
    m.querySelector('#account-logout').onclick = signOut;
  }
  function metricCard(value, label, tint) { return '<section class="metric-card ' + (tint || 'orange') + '"><strong>' + esc(value) + '</strong><span>' + esc(label) + '</span></section>'; }
  function progressLine(value) { return '<span class="completion"><span class="line"><i style="width:' + pct(value) + '%"></i></span><b>' + pct(value) + '%</b></span>'; }
  function studentRow(student, action) {
    return '<tr><td><div class="person"><span class="person-mark">' + initials(profileName(student)) + '</span><span><strong>' + esc(profileName(student)) + '</strong><small>' + esc(student.email || '') + '</small></span></div></td><td>' + progressLine(student.progress && student.progress.completion_percent) + '</td><td>' + esc(String((student.progress || {}).xp || 0)) + '</td><td>' + time((student.activity || {}).total_time_seconds) + '</td><td>' + esc(String((student.attempts || {}).total || 0)) + '</td><td><button class="btn ghost small" data-student="' + esc(student.id || '') + '">' + esc(action || 'View') + '</button></td></tr>';
  }
  function studentReport(student, section) {
    var progress = student.progress || {}, activity = student.activity || {}, attempts = student.attempts || {};
    var m = modal('<div class="control-eyebrow">Student learning record</div><h2>' + esc(profileName(student)) + '</h2><p class="modal-sub">' + esc((section.course_catalog || {}).code || '') + ' · ' + esc(section.section_label || '') + '</p><div class="account-grid">' + metricCard(pct(progress.completion_percent) + '%', 'Completion', 'orange') + metricCard(progress.xp || 0, 'XP earned', 'violet') + metricCard(time(activity.total_time_seconds), 'Active study', 'green') + metricCard(attempts.total || 0, 'Tutor attempts', 'blue') + '</div><section class="control-section"><div class="panel-head"><div><h2>Lesson progress</h2><p>Correct work and XP for each assigned lesson.</p></div></div><div class="review-lesson-list">' + ((progress.lessons || []).map(function (lesson) { return '<div class="review-lesson"><div><strong>' + esc(lesson.lesson_id) + '</strong><small>' + (lesson.solved || 0) + ' / ' + (lesson.target || 0) + ' problems · ' + (lesson.xp || 0) + ' XP</small></div>' + progressLine(lesson.completion_percent) + '</div>'; }).join('') || '<div class="empty-state">No lesson activity yet.</div>') + '</div></section><section class="control-section review-mini-grid"><div><strong>Practice and test</strong><span>Practice ' + time((activity.modes || {}).practice) + ' · Test ' + time((activity.modes || {}).test) + '</span></div><div><strong>Learning mode</strong><span>Learn ' + time((activity.modes || {}).learn) + ' · Study ' + time((activity.modes || {}).study) + '</span></div><div><strong>Delivery</strong><span>Online ' + time((activity.delivery || {}).online) + ' · Offline ' + time((activity.delivery || {}).offline) + '</span></div><div><strong>Calculator</strong><span>' + (activity.calculator_uses || 0) + ' recorded uses</span></div></section><div class="modal-actions"><button class="btn primary" data-close>Done</button></div>', { wide: true });
    return m;
  }
  async function authoredLessons(course) {
    var catalog = await fetch(new URL('../data/classes.json', import.meta.url)).then(function (r) { return r.ok ? r.json() : { classes: [] }; }).catch(function () { return { classes: [] }; });
    var authored = (catalog.classes || []).filter(function (item) { return String(item.code || '').toUpperCase() === String(course.code || '').toUpperCase(); })[0] || {};
    var index = await fetch(new URL('../data/index.json', import.meta.url)).then(function (r) { return r.ok ? r.json() : { lessons: [] }; }).catch(function () { return { lessons: [] }; });
    var listed = authored.lessons || course.lessons || [];
    return Promise.all(listed.map(async function (lesson) {
      var meta = (index.lessons || []).filter(function (item) { return item.id === lesson.id; })[0] || {};
      var body = meta.file ? await fetch(new URL('../data/' + meta.file, import.meta.url)).then(function (r) { return r.ok ? r.json() : {}; }).catch(function () { return {}; }) : {};
      return { id: lesson.id, title: meta.title || lesson.title || lesson.id, chapter: lesson.chapter || '', summary: body.summary || body.description || '', concepts: body.concepts || body.glossary && Object.keys(body.glossary) || [], problems: Array.isArray(lesson.problems) ? lesson.problems.length : Array.isArray(body.problems) ? body.problems.length : 0 };
    }));
  }
  async function reviewClass(classId) {
    var m = modal('<div class="review-loading">Loading this protected class record…</div>', { wide: true });
    try {
      var data = await Auth.api('/api/professor/classes?class_id=' + encodeURIComponent(classId));
      var section = data.section, course = section.course_catalog || {}, students = data.students || [], lessons = await authoredLessons(course);
      var active = students.filter(function (student) { return !!student.id; }), totals = active.reduce(function (memo, student) { memo.xp += n((student.progress || {}).xp); memo.time += n((student.activity || {}).total_time_seconds); memo.attempts += n((student.attempts || {}).total); memo.completion += n((student.progress || {}).completion_percent); return memo; }, { xp: 0, time: 0, attempts: 0, completion: 0 });
      m.innerHTML = '<div class="class-review"><div class="control-eyebrow">' + esc(course.subject || 'Course') + ' · protected class view</div><div class="class-review-title"><div><h2>' + esc(course.code || '') + ' — ' + esc(course.title || section.section_label) + '</h2><p class="modal-sub">' + esc(section.section_label) + (section.term ? ' · ' + esc(section.term) : '') + '</p></div><span class="panel-chip">' + students.length + ' enrolled</span></div><p class="review-description">' + esc(course.description || 'Review the lessons, class roster, and learning progress for this section.') + '</p><div class="account-grid review-metrics">' + metricCard(active.length, 'Active student accounts', 'green') + metricCard(active.length ? Math.round(totals.completion / active.length) + '%' : '—', 'Average completion', 'orange') + metricCard(totals.xp, 'Class XP', 'violet') + metricCard(time(totals.time), 'Recorded study time', 'blue') + '</div><div class="review-tabs"><button class="active" data-review-tab="content">Class content</button><button data-review-tab="students">Students (' + students.length + ')</button><button data-review-tab="activity">Activity</button></div><div id="review-body"></div><div class="modal-actions"><button class="btn subtle" data-close>Close</button></div></div>';
      var host = m.querySelector('#review-body');
      function content() {
        var books = Array.isArray(course.textbooks) ? course.textbooks : [];
        host.innerHTML = '<section class="review-textbooks"><strong>Course references</strong><span>' + esc(books.length ? books.join(' · ') : 'No textbook reference has been added yet.') + '</span></section><section class="review-lesson-list">' + (lessons.length ? lessons.map(function (lesson, index) { return '<article class="review-lesson"><span class="lesson-order">' + (index + 1) + '</span><div class="review-lesson-copy"><strong>' + esc(lesson.title) + '</strong><small>' + esc(lesson.chapter || 'Course lesson') + ' · ' + lesson.problems + ' assigned problems</small>' + (lesson.summary ? '<p>' + esc(lesson.summary) + '</p>' : '') + (lesson.concepts.length ? '<div class="concept-chips">' + lesson.concepts.slice(0, 6).map(function (concept) { return '<span>' + esc(typeof concept === 'string' ? concept : concept.title || concept.name || '') + '</span>'; }).join('') + '</div>' : '') + '</div></article>'; }).join('') : '<div class="empty-state">This class has no published lesson list yet. Add its lessons in the course content catalogue.</div>') + '</section>';
        if (window.StudyMath && window.StudyMath.render) window.StudyMath.render(host);
      }
      function studentsTab() {
        host.innerHTML = '<div class="data-table-wrap"><table class="control-table"><thead><tr><th>Student</th><th>Completion</th><th>XP</th><th>Time</th><th>Attempts</th><th></th></tr></thead><tbody>' + (students.length ? students.map(function (student) { return studentRow(student, student.id ? 'Open' : 'Invited'); }).join('') : '<tr><td colspan="6"><div class="empty-state">No students have been added yet.</div></td></tr>') + '</tbody></table></div>';
        host.querySelectorAll('[data-student]').forEach(function (button) { button.onclick = function () { var student = students.filter(function (item) { return item.id === button.dataset.student; })[0]; if (student) studentReport(student, section); }; });
      }
      function activity() {
        var sorted = active.slice().sort(function (a, b) { return n((b.activity || {}).total_time_seconds) - n((a.activity || {}).total_time_seconds); }), max = sorted.reduce(function (value, student) { return Math.max(value, n((student.activity || {}).total_time_seconds)); }, 0);
        host.innerHTML = '<div class="control-layout"><section class="control-panel"><div class="panel-head"><div><h2>Student activity</h2><p>Recorded active time in this class.</p></div></div>' + (max ? '<div class="activity-bars">' + sorted.slice(0, 8).map(function (student) { return '<span class="bar" style="--height:' + Math.max(10, Math.round(n((student.activity || {}).total_time_seconds) / max * 100)) + '%"><i>' + esc(profileName(student).slice(0, 8)) + '</i></span>'; }).join('') + '</div>' : '<div class="chart-empty">No study time has been recorded yet.</div>') + '</section><section class="control-panel"><div class="panel-head"><div><h2>Tutor and tools</h2><p>Use patterns, not private tutor chats.</p></div></div><div class="review-stat-list"><span><b>' + totals.attempts + '</b> tutor attempts</span><span><b>' + active.reduce(function (sum, student) { return sum + n((student.activity || {}).calculator_uses); }, 0) + '</b> calculator uses</span><span><b>' + time(active.reduce(function (sum, student) { return sum + n(((student.activity || {}).delivery || {}).online); }, 0)) + '</b> online study</span><span><b>' + time(active.reduce(function (sum, student) { return sum + n(((student.activity || {}).delivery || {}).offline); }, 0)) + '</b> offline study</span></div></section></div>';
      }
      var views = { content: content, students: studentsTab, activity: activity };
      m.querySelectorAll('[data-review-tab]').forEach(function (button) { button.onclick = function () { m.querySelectorAll('[data-review-tab]').forEach(function (item) { item.classList.toggle('active', item === button); }); views[button.dataset.reviewTab](); }; });
      content();
    } catch (reason) { m.innerHTML = error(reason.message); }
  }
  function openProfessorModal(done) {
    var m = modal('<h2>Add professor</h2><p class="modal-sub">They will be able to sign in with their email verification code.</p><form class="account-form" id="professor-form"><label>Email address<input type="email" name="email" required placeholder="professor@example.com"></label><div id="form-error"></div><div class="modal-actions"><button class="btn subtle" type="button" data-close>Cancel</button><button class="btn primary">Add professor</button></div></form>');
    m.querySelector('form').onsubmit = async function (event) { event.preventDefault(); try { await Auth.api('/api/admin/professors', { method: 'POST', body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); closeModal(); done(); } catch (reason) { m.querySelector('#form-error').innerHTML = error(reason.message); } };
  }
  function openCourseModal(done) {
    var m = modal('<h2>Add class to the catalogue</h2><p class="modal-sub">Professors can select it when creating their course section.</p><form class="account-form" id="course-form"><label>Course code<input name="code" required placeholder="CALC1"></label><label>Course title<input name="title" required placeholder="Calculus I"></label><label>Subject<input name="subject" required placeholder="calculus"></label><label>Description<textarea name="description" placeholder="A short course description"></textarea></label><div id="form-error"></div><div class="modal-actions"><button class="btn subtle" type="button" data-close>Cancel</button><button class="btn primary">Add class</button></div></form>');
    m.querySelector('form').onsubmit = async function (event) { event.preventDefault(); try { await Auth.api('/api/admin/courses', { method: 'POST', body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); closeModal(); done(); } catch (reason) { m.querySelector('#form-error').innerHTML = error(reason.message); } };
  }
  function roster(classId) {
    var m = modal('<h2>Student list</h2><div id="roster" class="account-empty">Loading student list…</div>'), host = m.querySelector('#roster');
    async function load() { try { var data = await Auth.api('/api/professor/students?class_id=' + encodeURIComponent(classId)); host.className = ''; host.innerHTML = '<form class="account-form" id="student-form"><label>Student email<input name="student_email" type="email" required placeholder="student@example.com"></label><div id="student-error"></div><button class="btn primary">Add student</button></form><div class="roster-list">' + ((data.students || []).map(function (student) { return '<div><span class="person-mark">' + initials((student.profiles || {}).display_name || student.student_email) + '</span><p><strong>' + esc((student.profiles || {}).display_name || student.student_email) + '</strong><small>' + esc(student.student_email) + ' · ' + esc(student.status) + '</small></p></div>'; }).join('') || '<div class="empty-state">No students yet.</div>') + '</div>'; host.querySelector('form').onsubmit = async function (event) { event.preventDefault(); try { await Auth.api('/api/professor/students', { method: 'POST', body: JSON.stringify({ class_id: classId, student_email: new FormData(event.currentTarget).get('student_email') }) }); load(); } catch (reason) { host.querySelector('#student-error').innerHTML = error(reason.message); } }; } catch (reason) { host.innerHTML = error(reason.message); } }
    load();
  }
  function workspace(target, title, subtitle) { target.innerHTML = '<div class="page wrap account-fallback"><div class="section-head"><div><h1>' + esc(title) + '</h1><p class="section-sub">' + esc(subtitle) + '</p></div></div><div id="account-body" class="account-body"><div class="account-empty">Loading…</div></div></div>'; return target.querySelector('#account-body'); }
  async function renderProfessor(target) {
    if (!account() || account().role !== 'professor') { target.innerHTML = '<div class="page wrap"><div class="account-empty">This area is available to professor accounts.</div></div>'; return; }
    var body = workspace(target, 'Professor workspace', 'Review your course content, student progress, attempts, XP, and completion in one place.');
    try {
      var loaded = await Promise.all([Auth.api('/api/catalog'), Auth.api('/api/professor/classes')]), catalog = loaded[0].courses || [], classes = loaded[1].classes || [];
      function draw() {
        body.innerHTML = '<div class="control-workspace"><aside class="control-nav"><div class="nav-mark">Σ</div><button class="active">My classes</button><div class="nav-bottom">Only you and StudyMAF administrators can see this student data.</div></aside><section class="control-main"><div class="control-hero"><div><div class="control-eyebrow">Teaching workspace</div><h1>See the whole class.</h1><p>Open a section to verify its lesson content and see live learning patterns—without reading private tutor conversations.</p></div></div><div class="control-layout"><section class="control-panel"><div class="panel-head"><div><h2>Create a class</h2><p>Students are added directly by email.</p></div></div><form class="account-form" id="class-form"><label>Class<select name="course_id" required><option value="">Choose a class</option>' + catalog.map(function (course) { return '<option value="' + esc(course.id) + '">' + esc(course.code + ' — ' + course.title) + '</option>'; }).join('') + '</select></label><label>Section name<input name="section_label" placeholder="Section 01" required></label><label>Term<input name="term" placeholder="Fall 2026"></label><div id="class-error"></div><button class="btn primary">Create class</button></form></section><section class="control-panel"><div class="panel-head"><div><h2>Your classes</h2><p>' + classes.length + ' class' + (classes.length === 1 ? '' : 'es') + '</p></div></div><div class="class-card-list">' + (classes.map(function (item) { var course = item.course_catalog || {}; return '<article><div><span class="role-pill">' + esc(course.subject || 'Course') + '</span><h3>' + esc(course.code || '') + ' · ' + esc(item.section_label) + '</h3><p>' + esc(course.title || '') + (item.term ? ' · ' + esc(item.term) : '') + '</p></div><div><button class="btn ghost small" data-roster="' + esc(item.id) + '">Students</button><button class="btn primary small" data-review="' + esc(item.id) + '">Open class</button></div></article>'; }).join('') || '<div class="empty-state">Create your first class to begin.</div>') + '</div></section></div></section></div>';
        body.querySelector('#class-form').onsubmit = async function (event) { event.preventDefault(); try { var saved = await Auth.api('/api/professor/classes', { method: 'POST', body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); saved.class.course_catalog = catalog.filter(function (course) { return course.id === saved.class.course_id; })[0]; classes.unshift(saved.class); draw(); } catch (reason) { body.querySelector('#class-error').innerHTML = error(reason.message); } };
        body.querySelectorAll('[data-roster]').forEach(function (button) { button.onclick = function () { roster(button.dataset.roster); }; });
        body.querySelectorAll('[data-review]').forEach(function (button) { button.onclick = function () { reviewClass(button.dataset.review); }; });
      }
      draw();
    } catch (reason) { body.innerHTML = error(reason.message); }
  }
  async function renderAdmin(target) {
    if (!account() || account().role !== 'admin') { target.innerHTML = '<div class="page wrap"><div class="account-empty">This area is only for StudyMAF administrators.</div></div>'; return; }
    target.innerHTML = '<div class="control-workspace"><aside class="control-nav"><div class="nav-mark">Σ</div><button class="active" data-view="overview">Overview</button><button data-view="people">People</button><button data-view="classes">Classes</button><button data-view="analytics">Analytics</button><div class="nav-bottom">Protected administrator workspace.<br>Student data stays server-side.</div></aside><main class="control-main" id="control-main"><div class="account-empty">Loading Control…</div></main></div>';
    try {
      var data = await Auth.api('/api/admin/dashboard'), users = data.users || [], classes = data.classes || [], enrollments = data.enrollments || [], roles = Object.fromEntries((data.roles || []).map(function (item) { return [item.user_id, item.role]; })), metrics = data.analytics && data.analytics.users || {}, main = target.querySelector('#control-main'), view = 'overview';
      function classCount(id) { return enrollments.filter(function (entry) { return entry.class_section_id === id && entry.status !== 'removed'; }).length; }
      function total(metric) { return users.reduce(function (sum, user) { return sum + n((metrics[user.id] || {})[metric]); }, 0); }
      function hero() { return '<div class="control-hero"><div><div class="control-eyebrow">Administrator workspace</div><h1>StudyMAF Control</h1><p>Open any class to inspect its published content and the learning progress of students who are enrolled.</p></div><div class="control-actions"><button class="btn primary" id="add-professor">+ Add professor</button><button class="btn ghost" id="add-course">Add class</button><button class="btn ghost" id="refresh">Refresh</button></div></div>'; }
      function userRow(user) { var metric = metrics[user.id] || {}; return '<tr><td><div class="person"><span class="person-mark">' + initials(profileName(user)) + '</span><span><strong>' + esc(profileName(user)) + '</strong><small>' + esc(user.email) + '</small></span></div></td><td><span class="role-pill">' + esc(roles[user.id] || 'student') + '</span></td><td>' + time(metric.total_time_seconds) + '</td><td>' + progressLine(metric.overall_completion_percent) + '</td><td><button class="btn ghost small" data-user="' + esc(user.id) + '">Open</button></td></tr>'; }
      function userReport(user) { var metric = metrics[user.id] || {}; modal('<div class="control-eyebrow">Account learning data</div><h2>' + esc(profileName(user)) + '</h2><p class="modal-sub">' + esc(user.email) + '</p><div class="account-grid">' + metricCard(time(metric.total_time_seconds), 'Active study time', 'green') + metricCard(metric.overall_completion_percent == null ? '—' : pct(metric.overall_completion_percent) + '%', 'Completion', 'orange') + metricCard(metric.calculator_uses || 0, 'Calculator use', 'blue') + '</div><section class="review-lesson-list">' + ((metric.classes || []).map(function (item) { return '<div class="review-lesson"><div><strong>' + esc(item.label) + '</strong><small>' + time(item.total_time_seconds) + ' active study</small></div>' + progressLine(item.completion_percent) + '</div>'; }).join('') || '<div class="empty-state">No learning activity recorded yet.</div>') + '</section><div class="modal-actions"><button class="btn primary" data-close>Done</button></div>', { wide: true }); }
      function overview() { return hero() + '<div class="control-metrics">' + metricCard(users.length, 'Verified accounts', 'orange') + metricCard(time(total('total_time_seconds')), 'Active study time', 'violet') + metricCard(classes.length, 'Professor classes', 'green') + metricCard((data.professor_invites || []).length, 'Pending professors', 'blue') + '</div><div class="control-layout"><section class="control-panel"><div class="panel-head"><div><h2>Recent class activity</h2><p>Class sections and enrollment at a glance.</p></div></div><div class="review-stat-list">' + (classes.slice(0, 6).map(function (section) { var course = section.course_catalog || {}; return '<button data-review="' + esc(section.id) + '"><span>' + esc(course.code || '') + ' · ' + esc(section.section_label) + '</span><b>' + classCount(section.id) + ' students</b></button>'; }).join('') || '<span>No classes yet.</span>') + '</div></section><section class="control-panel"><div class="panel-head"><div><h2>Learning modes</h2><p>Across all active accounts.</p></div></div><div class="review-stat-list"><span><b>' + time(users.reduce(function (sum, user) { return sum + n(((metrics[user.id] || {}).modes || {}).learn); }, 0)) + '</b> Learn</span><span><b>' + time(users.reduce(function (sum, user) { return sum + n(((metrics[user.id] || {}).modes || {}).practice); }, 0)) + '</b> Practice</span><span><b>' + time(users.reduce(function (sum, user) { return sum + n(((metrics[user.id] || {}).modes || {}).test); }, 0)) + '</b> Test</span></div></section></div>'; }
      function people() { return hero() + '<section class="control-section"><div class="section-row"><div><h2>Accounts and learning data</h2><p>Open an account for its private learning summary.</p></div></div><div class="data-table-wrap"><table class="control-table"><thead><tr><th>Account</th><th>Role</th><th>Time</th><th>Completion</th><th></th></tr></thead><tbody>' + (users.map(userRow).join('') || '<tr><td colspan="5">No accounts yet.</td></tr>') + '</tbody></table></div></section>'; }
      function classesView() { return hero() + '<section class="control-section"><div class="section-row"><div><h2>All classes</h2><p>View course content and student learning data for any class.</p></div></div><div class="class-card-list admin-classes">' + (classes.map(function (section) { var course = section.course_catalog || {}, professor = section.profiles || {}; return '<article><div><span class="role-pill">' + esc(course.subject || 'Course') + '</span><h3>' + esc(course.code || '') + ' · ' + esc(section.section_label) + '</h3><p>' + esc(course.title || '') + ' · ' + esc(professor.display_name || professor.email || 'No professor') + '</p></div><div><small>' + classCount(section.id) + ' students</small><button class="btn primary small" data-review="' + esc(section.id) + '">Open class</button></div></article>'; }).join('') || '<div class="empty-state">No professor classes exist yet.</div>') + '</div></section>'; }
      function analytics() { return hero() + '<div class="control-layout"><section class="control-panel"><div class="panel-head"><div><h2>Study delivery</h2><p>Online versus offline time.</p></div></div><div class="review-stat-list"><span><b>' + time(users.reduce(function (sum, user) { return sum + n((((metrics[user.id] || {}).delivery || {}).online)); }, 0)) + '</b> Online</span><span><b>' + time(users.reduce(function (sum, user) { return sum + n((((metrics[user.id] || {}).delivery || {}).offline)); }, 0)) + '</b> Offline</span></div></section><section class="control-panel"><div class="panel-head"><div><h2>Calculator use</h2><p>Tracked without storing expressions.</p></div></div><div class="chart-empty"><strong style="font-size:2rem;color:var(--ink)">' + total('calculator_uses') + '</strong><br>Recorded calculator uses</div></section></div><section class="control-section"><div class="section-row"><div><h2>Per-account analytics</h2><p>Open an account for its private learning summary.</p></div></div><div class="data-table-wrap"><table class="control-table"><thead><tr><th>Account</th><th>Role</th><th>Time</th><th>Completion</th><th></th></tr></thead><tbody>' + (users.map(userRow).join('') || '<tr><td colspan="5">No accounts yet.</td></tr>') + '</tbody></table></div></section>'; }
      function bind() { main.querySelectorAll('[data-review]').forEach(function (button) { button.onclick = function () { reviewClass(button.dataset.review); }; }); main.querySelectorAll('[data-user]').forEach(function (button) { button.onclick = function () { userReport(users.filter(function (user) { return user.id === button.dataset.user; })[0]); }; }); var refresh = main.querySelector('#refresh'); if (refresh) refresh.onclick = function () { renderAdmin(target); }; var professor = main.querySelector('#add-professor'); if (professor) professor.onclick = function () { openProfessorModal(function () { renderAdmin(target); }); }; var course = main.querySelector('#add-course'); if (course) course.onclick = function () { openCourseModal(function () { renderAdmin(target); }); }; }
      function draw() { main.innerHTML = view === 'people' ? people() : view === 'classes' ? classesView() : view === 'analytics' ? analytics() : overview(); bind(); target.querySelectorAll('[data-view]').forEach(function (button) { button.classList.toggle('active', button.dataset.view === view); button.onclick = function () { view = button.dataset.view; draw(); }; }); }
      draw();
    } catch (reason) { target.querySelector('#control-main').innerHTML = error(reason.message); }
  }
  return { ready: function () { return Auth.init(); }, mountHeader: function () { var nav = document.querySelector('.header-actions'); if (!nav) return; header = document.createElement('button'); header.className = 'btn ghost account-header-name'; header.type = 'button'; header.onclick = openAccount; nav.appendChild(header); syncHeader(); Auth.onChange(syncHeader); }, openSignIn: function () { location.assign(rootUrl('signin/')); }, renderProfessor: renderProfessor, renderAdmin: renderAdmin, account: account, openAccount: openAccount };
}
