import { Auth } from './auth.js';

function esc(value) { return String(value == null ? '' : value).replace(/[&<>"']/g, function (c) { return ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]; }); }
function n(value) { return Math.max(0, Number(value) || 0); }
function pct(value) { return Math.max(0, Math.min(100, Math.round(n(value)))); }
function time(value) { value = Math.round(n(value)); if (value < 60) return value ? '<1m' : '0m'; var h = Math.floor(value / 3600), m = Math.round(value % 3600 / 60); return h ? h + 'h ' + m + 'm' : m + 'm'; }
function initials(value) { return String(value || '?').trim().split(/\s+|@/).map(function (part) { return part.charAt(0); }).join('').slice(0, 2).toUpperCase(); }
function rootUrl(path) { return new URL(path, new URL('../', import.meta.url)).href; }
function profileName(person) { return (person && (person.display_name || person.name || person.email)) || 'Student'; }
function roleName(role) { return role === 'admin' ? 'Administrator' : role === 'professor' ? 'Professor' : 'Student'; }
function courseLabel(course) { var code = String(course && course.code || '').trim(), title = String(course && course.title || '').trim(); return code && title && title.toUpperCase().indexOf(code.toUpperCase()) === 0 ? title : [code, title].filter(Boolean).join(' — '); }
function renderMath(node) { if (!node) return; if (window.StudyMath && window.StudyMath.render) return window.StudyMath.render(node); if (window.renderMathInElement) window.renderMathInElement(node, { delimiters: [{ left: '$$', right: '$$', display: true }, { left: '$', right: '$', display: false }], throwOnError: false }); }
function sourceDocumentsHtml(course, options) {
  options = options || {};
  var documents = Array.isArray(course && course.course_documents) ? course.course_documents : [];
  if (!documents.length) return '<section class="review-textbooks source-document-empty"><strong>Private course files</strong><span>No source PDFs have been uploaded for this course yet.</span>' + (options.upload ? '<button class="btn primary small" data-source-upload="' + esc(course.id || '') + '">Upload source PDFs</button>' : '') + '</section>';
  return '<section class="review-textbooks source-document-list"><strong>Private course files</strong><span>Files are stored privately and each link expires shortly after it is opened.</span><div class="source-download-grid">' + documents.map(function (document) { return '<a class="source-download" href="' + esc(document.download_url || '#') + '" target="_blank" rel="noopener"><span class="source-kind">' + esc(document.kind === 'syllabus' ? 'Syllabus' : 'Textbook') + '</span><strong>' + esc(document.original_name || 'Course PDF') + '</strong><b>Download PDF <span aria-hidden="true">↓</span></b></a>'; }).join('') + '</div></section>';
}

export function createAccountUI(options) {
  var modal = options.modal, closeModal = options.closeModal, header;
  function account() { return Auth.getAccount(); }
  function error(message) { return '<p class="account-error">' + esc(message || 'Something went wrong.') + '</p>'; }
  function dashboardUrl() { return rootUrl(account() && account().role === 'admin' ? 'control/' : 'dashboard/'); }
  async function signOut() { await Auth.signOut(); closeModal(); location.assign(rootUrl('signin/')); }

  function syncHeader() {
    if (!header) return;
    var a = account(); header.hidden = !a;
    if (!a) return;
    header.innerHTML = '<span class="account-avatar">' + initials(a.user.name || a.user.email) + '</span><span class="account-header-label">' + esc((a.user.name || a.user.email).split(' ')[0]) + '</span>';
    header.setAttribute('aria-label', 'Open account menu for ' + a.user.email);
  }
  function openSettings() {
    var a = account(); if (!a) return;
    var m = modal('<div class="control-eyebrow">Account settings</div><h2>Your profile</h2><p class="modal-sub">Your name appears in authorized teaching and administrator workspaces.</p><form class="account-form" id="profile-form"><label>Display name<input name="display_name" maxlength="80" value="' + esc(a.user.name || '') + '" placeholder="Your name"></label><label>Email address<input value="' + esc(a.user.email) + '" disabled></label><div id="profile-error"></div><div class="modal-actions"><button class="btn subtle" type="button" data-close>Cancel</button><button class="btn primary" type="submit">Save settings</button></div></form>');
    m.querySelector('#profile-form').onsubmit = async function (event) {
      event.preventDefault(); var form = event.currentTarget;
      try { await Auth.api('/api/account/me', { method: 'PATCH', body: JSON.stringify({ display_name: new FormData(form).get('display_name') }) }); await Auth.init(); syncHeader(); closeModal(); }
      catch (reason) { m.querySelector('#profile-error').innerHTML = error(reason.message); }
    };
  }
  function openAccount() {
    var a = account(); if (!a) return;
    var m = modal('<div class="account-menu-head"><span class="account-avatar large">' + initials(a.user.name || a.user.email) + '</span><div><strong>' + esc(a.user.name || a.user.email) + '</strong><p>' + esc(a.user.email) + '</p></div></div><span class="role-pill">' + esc(roleName(a.role)) + '</span><div class="account-menu-actions"><button class="btn primary" id="account-dashboard">Dashboard</button><button class="btn ghost" id="account-settings">Settings</button><button class="btn danger" id="account-logout">Sign out</button></div>');
    m.querySelector('#account-dashboard').onclick = function () { location.assign(dashboardUrl()); };
    m.querySelector('#account-settings').onclick = openSettings;
    m.querySelector('#account-logout').onclick = signOut;
  }
  function metricCard(value, label, tint) { return '<section class="metric-card ' + (tint || 'orange') + '"><strong>' + esc(value) + '</strong><span>' + esc(label) + '</span></section>'; }
  function progressLine(value) { return '<span class="completion"><span class="line"><i style="width:' + pct(value) + '%"></i></span><b>' + pct(value) + '%</b></span>'; }
  function studentRow(student, action) {
    return '<tr><td><div class="person"><span class="person-mark">' + initials(profileName(student)) + '</span><span><strong>' + esc(profileName(student)) + '</strong><small>' + esc(student.email || '') + '</small></span></div></td><td>' + progressLine(student.progress && student.progress.completion_percent) + '</td><td>' + esc(String((student.progress || {}).xp || 0)) + '</td><td>' + time((student.activity || {}).total_time_seconds) + '</td><td>' + esc(String((student.attempts || {}).total || 0)) + '</td><td><button class="btn ghost small" data-student="' + esc(student.id || '') + '">' + esc(action || 'View') + '</button></td></tr>';
  }
  function studentReport(student, section) {
    var progress = student.progress || {}, activity = student.activity || {}, attempts = student.attempts || {};
    var m = modal('<div class="control-eyebrow">Student learning record</div><h2>' + esc(profileName(student)) + '</h2><p class="modal-sub">' + esc((section.course_catalog || {}).code || '') + ' · ' + esc(section.section_label || '') + '</p><div class="account-grid">' + metricCard(pct(progress.completion_percent) + '%', 'Completion', 'orange') + metricCard(progress.xp || 0, 'XP earned', 'violet') + metricCard(time(activity.total_time_seconds), 'Active study', 'green') + metricCard(attempts.total || 0, 'Tutor attempts', 'blue') + '</div><section class="control-section"><div class="panel-head"><div><h2>Lesson progress</h2><p>Correct work and XP for each assigned lesson.</p></div></div><div class="review-lesson-list">' + ((progress.lessons || []).map(function (lesson) { return '<div class="review-lesson"><div><strong>' + esc(lesson.lesson_id) + '</strong><small>' + (lesson.solved || 0) + ' / ' + (lesson.target || 0) + ' problems · ' + (lesson.xp || 0) + ' XP</small></div>' + progressLine(lesson.completion_percent) + '</div>'; }).join('') || '<div class="empty-state">No lesson activity yet.</div>') + '</div></section><section class="control-section review-mini-grid"><div><strong>Practice and test</strong><span>Practice ' + time((activity.modes || {}).practice) + ' · Test ' + time((activity.modes || {}).test) + '</span></div><div><strong>Learning mode</strong><span>Learn ' + time((activity.modes || {}).learn) + ' · Study ' + time((activity.modes || {}).study) + '</span></div><div><strong>Delivery</strong><span>Online ' + time((activity.delivery || {}).online) + ' · Offline ' + time((activity.delivery || {}).offline) + '</span></div><div><strong>Calculator</strong><span>' + (activity.calculator_uses || 0) + ' recorded uses</span></div></section><div class="modal-actions"><button class="btn primary" data-close>Done</button></div>', { wide: true });
    return m;
  }
  async function authoredLessons(course) {
    var catalog = await fetch(new URL('../data/classes.json', import.meta.url)).then(function (r) { return r.ok ? r.json() : { classes: [] }; }).catch(function () { return { classes: [] }; });
    var authored = (catalog.classes || []).filter(function (item) { return String(item.code || '').toUpperCase() === String(course.code || '').toUpperCase(); })[0] || {};
    var index = await fetch(new URL('../data/index.json', import.meta.url)).then(function (r) { return r.ok ? r.json() : { lessons: [] }; }).catch(function () { return { lessons: [] }; });
    var listed = authored.lessons || course.lessons || [];
    return Promise.all(listed.map(async function (lesson) {
      var meta = (index.lessons || []).filter(function (item) { return item.id === lesson.id; })[0] || {};
      var body = meta.file ? await fetch(new URL('../data/' + meta.file, import.meta.url)).then(function (r) { return r.ok ? r.json() : {}; }).catch(function () { return {}; }) : {};
      return { id: lesson.id, title: meta.title || lesson.title || lesson.id, chapter: lesson.chapter || '', summary: body.summary || body.description || '', concepts: body.concepts || body.glossary && Object.keys(body.glossary) || [], problems: Array.isArray(lesson.problems) ? lesson.problems.length : Array.isArray(body.problems) ? body.problems.length : 0, practiceProblems: Array.isArray(body.problems) ? body.problems : [], learnConcepts: Array.isArray(body.concept_sections) ? body.concept_sections : [] };
    }));
  }
  async function reviewClass(classId, coursePreview) {
    var m = modal('<div class="review-loading">Loading this protected class record…</div>', { wide: true });
    try {
      var data;
      if (coursePreview) {
        var courseEndpoint = account() && account().role === 'admin' ? '/api/admin/courses?course_id=' : '/api/catalog?course_id=';
        var courseResult = await Auth.api(courseEndpoint + encodeURIComponent(coursePreview.id));
        data = { section: { section_label: 'Course library', term: '', course_catalog: courseResult.course || coursePreview }, students: [] };
      } else data = await Auth.api('/api/professor/classes?class_id=' + encodeURIComponent(classId));
      var section = data.section, course = section.course_catalog || {}, students = data.students || [], lessons = await authoredLessons(course), canManageSources = !!coursePreview && !!account() && account().role === 'admin';
      var active = students.filter(function (student) { return !!student.id; }), totals = active.reduce(function (memo, student) { memo.xp += n((student.progress || {}).xp); memo.time += n((student.activity || {}).total_time_seconds); memo.attempts += n((student.attempts || {}).total); memo.completion += n((student.progress || {}).completion_percent); return memo; }, { xp: 0, time: 0, attempts: 0, completion: 0 });
      var tabs = '<button class="active" data-review-tab="content">Class content</button><button data-review-tab="sources">Source files</button>' + (coursePreview ? '' : '<button data-review-tab="students">Students (' + students.length + ')</button><button data-review-tab="activity">Activity</button>');
      m.innerHTML = '<button class="modal-x" type="button" aria-label="Close" data-close>×</button><div class="class-review"><div class="control-eyebrow">' + esc(course.subject || 'Course') + ' · ' + (coursePreview ? 'course library preview' : 'protected class view') + '</div><div class="class-review-title"><div><h2>' + esc(courseLabel(course) || section.section_label) + '</h2><p class="modal-sub">' + esc(section.section_label) + (section.term ? ' · ' + esc(section.term) : '') + '</p></div><span class="panel-chip">' + students.length + ' enrolled</span></div><p class="review-description">' + esc(course.description || 'Review the same lesson structure students use. Preview work never changes student progress, XP, or attempts.') + '</p><div class="account-grid review-metrics">' + metricCard(active.length, 'Active student accounts', 'green') + metricCard(active.length ? Math.round(totals.completion / active.length) + '%' : '—', 'Average completion', 'orange') + metricCard(totals.xp, 'Class XP', 'violet') + metricCard(time(totals.time), 'Recorded study time', 'blue') + '</div><div class="review-tabs">' + tabs + '</div><div id="review-body"></div><div class="modal-actions"><button class="btn subtle" data-close>Close</button></div></div>';
      var host = m.querySelector('#review-body');
      function content() {
        var books = Array.isArray(course.textbooks) ? course.textbooks : [];
        host.innerHTML = '<section class="review-textbooks"><strong>Course references</strong><span>' + esc(books.length ? books.join(' · ') : 'No textbook reference has been added yet.') + '</span></section>' + sourceDocumentsHtml(course, { upload: canManageSources }) + '<p class="review-flow-note">Open a lesson exactly as a student would, then use <strong>Learn</strong>, <strong>Practice</strong>, or <strong>Test Mode</strong> to review its material.</p><section class="lesson-list review-lesson-list">' + (lessons.length ? lessons.map(function (lesson, index) { return '<article class="lesson reviewer-lesson" aria-expanded="false"><button class="lesson-btn" type="button" data-review-lesson="' + esc(lesson.id) + '"><span class="lesson-idx">' + (index + 1) + '</span><span class="lesson-main"><span class="name">Lesson ' + (index + 1) + ': ' + esc(lesson.title) + '</span><span class="mini-progress"><span class="progress-track"><span class="progress-fill" style="width:0%"></span></span><span class="progress-pct">' + lesson.problems + ' questions</span><span class="lesson-xp">Preview only</span>' + (lesson.chapter ? '<span class="lesson-chapter">' + esc(lesson.chapter) + '</span>' : '') + '</span></span><span class="lesson-caret" aria-hidden="true">›</span></button><div class="lesson-panel" hidden data-review-panel="' + esc(lesson.id) + '"></div></article>'; }).join('') : '<div class="empty-state">This class has no published lesson list yet. Add its lessons in the course content catalogue.</div>') + '</section>';
        host.querySelectorAll('[data-review-lesson]').forEach(function (button) { button.onclick = function () { var row = button.closest('.reviewer-lesson'), panel = row.querySelector('[data-review-panel]'), open = row.getAttribute('aria-expanded') === 'true', lesson = lessons.filter(function (item) { return item.id === button.dataset.reviewLesson; })[0]; row.setAttribute('aria-expanded', String(!open)); panel.hidden = open; if (!open && lesson && !panel.dataset.loaded) { panel.dataset.loaded = 'true'; renderLessonPanel(lesson, panel); } }; });
        host.querySelectorAll('[data-source-upload]').forEach(function (button) { button.onclick = function () { openSourceUploadModal(course, function () { closeModal(); reviewClass('', course); }); }; });
        renderMath(host);
      }
      function generatedFields(instance) { if (instance.type === 'mc') return '<div class="preview-choices">' + (instance.choices || []).map(function (choice, index) { return '<label><input type="radio" name="instructor-choice" value="' + index + '"><span>' + esc(choice) + '</span></label>'; }).join('') + '</div>'; if (instance.type === 'multi') return '<div class="preview-parts">' + (instance.parts || []).map(function (part, index) { return '<label>' + esc(part.label || 'Part ' + (index + 1)) + (part.type === 'mc' ? '<select data-preview-part="' + index + '"><option value="">Choose an answer</option>' + (part.choices || []).map(function (choice, choiceIndex) { return '<option value="' + choiceIndex + '">' + esc(choice) + '</option>'; }).join('') + '</select>' : '<input data-preview-part="' + index + '" inputmode="decimal" placeholder="Your answer" autocomplete="off">') + '</label>'; }).join('') + '</div>'; return '<label class="preview-answer-label">Your answer<input data-preview-number inputmode="decimal" placeholder="Enter a number" autocomplete="off"><small>' + esc(instance.unit || '') + '</small></label>'; }
      function generatedAnswer(instance) { if (instance.type === 'mc') return esc((instance.choices || [])[instance.answerIndex] || ''); if (instance.type === 'multi') return (instance.parts || []).map(function (part, index) { return '<li><strong>' + esc(part.label || 'Part ' + (index + 1)) + ':</strong> ' + esc(part.type === 'mc' ? (part.choices || [])[part.answerIndex] || '' : part.answerText || '') + '</li>'; }).join(''); return esc(instance.answerText || ''); }
      function checkGenerated(instance, zone) { var correct = false; if (instance.type === 'mc') { var selected = zone.querySelector('input[name="instructor-choice"]:checked'); correct = !!selected && Number(selected.value) === Number(instance.answerIndex); } else if (instance.type === 'multi') { correct = (instance.parts || []).every(function (part, index) { var field = zone.querySelector('[data-preview-part="' + index + '"]'); if (!field || field.value === '') return false; if (part.type === 'mc') return Number(field.value) === Number(part.answerIndex); var value = Number(field.value), target = Number(part.answerValue), tolerance = Number(part.tol || .03); return isFinite(value) && Math.abs(value - target) <= Math.max(1, Math.abs(target)) * tolerance; }); } else { var answer = Number((zone.querySelector('[data-preview-number]') || {}).value), target = Number(instance.answerValue), tolerance = Number(instance.tol || .03); correct = isFinite(answer) && Math.abs(answer - target) <= Math.max(1, Math.abs(target)) * tolerance; } var verdict = zone.querySelector('.instructor-verdict'), solution = zone.querySelector('.instructor-solution'); verdict.textContent = correct ? 'Correct — this preview does not change any student data.' : 'Review the answer and steps below. This preview does not change any student data.'; verdict.className = 'instructor-verdict ' + (correct ? 'right' : 'wrong'); solution.hidden = false; renderMath(solution); }
      function renderGeneratedPreview(lesson, zone, selectedDifficulty) { var engine = window.Generators, difficulties = engine && engine.difficulties ? engine.difficulties(lesson.id) : [], difficulty = selectedDifficulty && selectedDifficulty !== 'mixed' ? selectedDifficulty : difficulties[Math.min(1, Math.max(0, difficulties.length - 1))] || difficulties[0] || 'medium', instance = engine && engine.make ? engine.make(lesson.id, difficulty) : null; if (!instance) { zone.innerHTML = '<div class="empty-state">This lesson does not have a generated Learn check available yet.</div>'; return; } zone.innerHTML = '<div class="instructor-question"><div class="preview-question-head"><span class="role-pill">Learn preview</span><span class="panel-chip">' + esc(instance.difficulty || difficulty) + '</span></div><div class="preview-prompt">' + esc(instance.prompt) + '</div>' + generatedFields(instance) + '<div class="preview-actions"><button class="btn primary small" data-check-generated>Check answer</button><button class="btn ghost small" data-refresh-generated>New question</button></div><p class="instructor-verdict" aria-live="polite"></p><section class="instructor-solution" hidden><strong>Answer</strong><div class="solution-answer">' + (instance.type === 'multi' ? '<ol>' + generatedAnswer(instance) + '</ol>' : generatedAnswer(instance)) + '</div><strong>Worked steps</strong><ol>' + (instance.steps || []).map(function (step) { return '<li>' + esc(step) + '</li>'; }).join('') + '</ol></section></div>'; renderMath(zone); zone.querySelector('[data-check-generated]').onclick = function () { checkGenerated(instance, zone); }; zone.querySelector('[data-refresh-generated]').onclick = function () { renderGeneratedPreview(lesson, zone, selectedDifficulty); }; }
      function renderStaticPreview(lesson, zone, mode) {
        var problems = lesson.practiceProblems || [], limit = mode === 'test' ? Math.min(3, problems.length) : 1;
        if (!problems.length) { zone.innerHTML = '<div class="empty-state">No authored ' + (mode === 'test' ? 'Test Mode' : 'Practice') + ' questions are available for this lesson yet.</div>'; return; }
        zone.innerHTML = '<section class="instructor-preview-intro compact"><div><span class="role-pill">' + (mode === 'test' ? 'Test Mode preview' : 'Practice preview') + '</span><p>' + (mode === 'test' ? 'A short, non-recorded test set. Work each question, then check the official answer and steps.' : 'The same authored practice material students see. This does not affect any account.') + '</p></div></section><div class="practice-preview-list">' + problems.slice(0, limit).map(function (problem, index) { return '<article class="practice-preview-problem"><div class="preview-question-head"><span class="panel-chip">Question ' + (index + 1) + '</span><span class="role-pill">' + esc(problem.difficulty || mode) + '</span></div><div class="preview-prompt">' + esc(problem.prompt || '') + '</div><label class="preview-answer-label">Your answer<input data-practice-answer="' + esc(lesson.id) + '-' + mode + '-' + index + '" placeholder="Work it out, then check" autocomplete="off"></label><div class="preview-actions"><button class="btn primary small" data-reveal-practice="' + esc(lesson.id) + '-' + mode + '-' + index + '">Check answer and steps</button></div><section class="instructor-solution" data-practice-solution="' + esc(lesson.id) + '-' + mode + '-' + index + '" hidden><strong>Official answer</strong><div class="solution-answer">' + esc(problem.correct_answer || '') + '</div><strong>Worked steps</strong><ol>' + (problem.solution_steps || []).map(function (step) { return '<li>' + esc(step) + '</li>'; }).join('') + '</ol></section></article>'; }).join('') + '</div>';
        renderMath(zone);
        zone.querySelectorAll('[data-reveal-practice]').forEach(function (button) { button.onclick = function () { var solution = zone.querySelector('[data-practice-solution="' + button.dataset.revealPractice + '"]'); if (solution) { solution.hidden = false; renderMath(solution); button.textContent = 'Answer shown'; button.disabled = true; } }; });
      }
      function renderLessonPanel(lesson, panel) {
        var engine = window.Generators, difficulties = engine && engine.difficulties ? engine.difficulties(lesson.id) : [], selected = 'mixed';
        panel.innerHTML = (lesson.summary ? '<p class="lp-summary">' + esc(lesson.summary) + '</p>' : '') + (lesson.concepts && lesson.concepts.length ? '<div class="concept-chips">' + lesson.concepts.slice(0, 6).map(function (concept) { return '<span>' + esc(typeof concept === 'string' ? concept : concept.title || concept.name || '') + '</span>'; }).join('') + '</div>' : '') + (difficulties.length ? '<div class="lp-diff"><span class="lp-diff-label">Difficulty</span>' + [{ value: 'mixed', label: 'Mixed' }].concat(difficulties.map(function (value) { return { value: value, label: String(value).charAt(0).toUpperCase() + String(value).slice(1) }; })).map(function (item) { return '<button type="button" class="lp-pill' + (item.value === selected ? ' on' : '') + '" data-review-difficulty="' + esc(item.value) + '">' + esc(item.label) + '</button>'; }).join('') + '</div>' : '') + '<div class="lp-actions"><button type="button" class="btn primary" data-review-mode="learn">Learn</button><button type="button" class="btn ghost" data-review-mode="practice">Practice</button><button type="button" class="btn ghost" data-review-mode="test">Test Mode</button></div><div class="review-mode-slot" aria-live="polite"></div>';
        panel.querySelectorAll('[data-review-difficulty]').forEach(function (button) { button.onclick = function () { selected = button.dataset.reviewDifficulty; panel.querySelectorAll('[data-review-difficulty]').forEach(function (item) { item.classList.toggle('on', item === button); }); }; });
        panel.querySelectorAll('[data-review-mode]').forEach(function (button) { button.onclick = function () { var zone = panel.querySelector('.review-mode-slot'); if (button.dataset.reviewMode === 'learn') { renderGeneratedPreview(lesson, zone, selected); } else { renderStaticPreview(lesson, zone, button.dataset.reviewMode); } }; });
        renderMath(panel);
      }
      function learnChecks() { host.innerHTML = '<section class="instructor-preview-intro"><div><span class="role-pill">Instructor preview</span><h3>Learn checks</h3><p>These use the same question generator as Learn mode. Work a fresh question, check it, and inspect the steps. Nothing here adds progress, XP, attempts, or activity.</p></div></section><div class="instructor-lesson-list">' + lessons.map(function (lesson) { return '<article class="instructor-lesson"><div><strong>' + esc(lesson.title) + '</strong><small>' + esc(lesson.chapter || 'Course lesson') + ' · ' + (lesson.learnConcepts || []).length + ' concepts</small></div><button class="btn primary small" data-start-learn="' + esc(lesson.id) + '">Try a Learn check</button><div class="instructor-question-slot" data-learn-slot="' + esc(lesson.id) + '"></div></article>'; }).join('') + '</div>'; host.querySelectorAll('[data-start-learn]').forEach(function (button) { button.onclick = function () { var lesson = lessons.filter(function (item) { return item.id === button.dataset.startLearn; })[0], zone = host.querySelector('[data-learn-slot="' + button.dataset.startLearn + '"]'); if (lesson && zone) renderGeneratedPreview(lesson, zone); }; }); }
      function practiceProblems() { host.innerHTML = '<section class="instructor-preview-intro"><div><span class="role-pill">Instructor preview</span><h3>Practice problems</h3><p>These are the authored practice problems students see. Enter your work, then reveal the official answer and steps. This preview never changes progress or class analytics.</p></div></section><div class="practice-preview-list">' + lessons.map(function (lesson) { return '<section class="practice-preview-lesson"><h3>' + esc(lesson.title) + '</h3><p>' + esc(lesson.chapter || 'Course lesson') + '</p>' + ((lesson.practiceProblems || []).map(function (problem, index) { return '<article class="practice-preview-problem"><div class="preview-question-head"><span class="panel-chip">Problem ' + (index + 1) + '</span><span class="role-pill">' + esc(problem.difficulty || 'practice') + '</span></div><div class="preview-prompt">' + esc(problem.prompt || '') + '</div><label class="preview-answer-label">Your answer<input data-practice-answer="' + esc(lesson.id) + '-' + index + '" placeholder="Work it out, then check" autocomplete="off"></label><div class="preview-actions"><button class="btn primary small" data-reveal-practice="' + esc(lesson.id) + '" data-problem-index="' + index + '">Check answer and steps</button></div><section class="instructor-solution" data-practice-solution="' + esc(lesson.id) + '-' + index + '" hidden><strong>Official answer</strong><div class="solution-answer">' + esc(problem.correct_answer || '') + '</div><strong>Worked steps</strong><ol>' + (problem.solution_steps || []).map(function (step) { return '<li>' + esc(step) + '</li>'; }).join('') + '</ol></section></article>'; }).join('') || '<div class="empty-state">No authored practice problems are available for this lesson yet.</div>') + '</section>'; }).join('') + '</div>'; renderMath(host); host.querySelectorAll('[data-reveal-practice]').forEach(function (button) { button.onclick = function () { var solution = host.querySelector('[data-practice-solution="' + button.dataset.revealPractice + '-' + button.dataset.problemIndex + '"]'); if (solution) { solution.hidden = false; renderMath(solution); button.textContent = 'Answer shown'; button.disabled = true; } }; }); }
      function studentsTab() {
        host.innerHTML = '<div class="data-table-wrap"><table class="control-table"><thead><tr><th>Student</th><th>Completion</th><th>XP</th><th>Time</th><th>Attempts</th><th></th></tr></thead><tbody>' + (students.length ? students.map(function (student) { return studentRow(student, student.id ? 'Open' : 'Invited'); }).join('') : '<tr><td colspan="6"><div class="empty-state">No students have been added yet.</div></td></tr>') + '</tbody></table></div>';
        host.querySelectorAll('[data-student]').forEach(function (button) { button.onclick = function () { var student = students.filter(function (item) { return item.id === button.dataset.student; })[0]; if (student) studentReport(student, section); }; });
      }
      function activity() {
        var sorted = active.slice().sort(function (a, b) { return n((b.activity || {}).total_time_seconds) - n((a.activity || {}).total_time_seconds); }), max = sorted.reduce(function (value, student) { return Math.max(value, n((student.activity || {}).total_time_seconds)); }, 0);
        host.innerHTML = '<div class="control-layout"><section class="control-panel"><div class="panel-head"><div><h2>Student activity</h2><p>Recorded active time in this class.</p></div></div>' + (max ? '<div class="activity-bars">' + sorted.slice(0, 8).map(function (student) { return '<span class="bar" style="--height:' + Math.max(10, Math.round(n((student.activity || {}).total_time_seconds) / max * 100)) + '%"><i>' + esc(profileName(student).slice(0, 8)) + '</i></span>'; }).join('') + '</div>' : '<div class="chart-empty">No study time has been recorded yet.</div>') + '</section><section class="control-panel"><div class="panel-head"><div><h2>Tutor and tools</h2><p>Use patterns, not private tutor chats.</p></div></div><div class="review-stat-list"><span><b>' + totals.attempts + '</b> tutor attempts</span><span><b>' + active.reduce(function (sum, student) { return sum + n((student.activity || {}).calculator_uses); }, 0) + '</b> calculator uses</span><span><b>' + time(active.reduce(function (sum, student) { return sum + n(((student.activity || {}).delivery || {}).online); }, 0)) + '</b> online study</span><span><b>' + time(active.reduce(function (sum, student) { return sum + n(((student.activity || {}).delivery || {}).offline); }, 0)) + '</b> offline study</span></div></section></div>';
      }
      function sources() { host.innerHTML = sourceDocumentsHtml(course, { upload: canManageSources }); host.querySelectorAll('[data-source-upload]').forEach(function (button) { button.onclick = function () { openSourceUploadModal(course, function () { closeModal(); reviewClass('', course); }); }; }); }
      var views = { content: content, sources: sources, students: studentsTab, activity: activity };
      m.querySelectorAll('[data-review-tab]').forEach(function (button) { button.onclick = function () { m.querySelectorAll('[data-review-tab]').forEach(function (item) { item.classList.toggle('active', item === button); }); views[button.dataset.reviewTab](); }; });
      content();
    } catch (reason) { m.innerHTML = error(reason.message); }
  }
  function openProfessorModal(done) {
    var m = modal('<h2>Add professor</h2><p class="modal-sub">They will be able to sign in with their email verification code.</p><form class="account-form" id="professor-form"><label>Email address<input type="email" name="email" required placeholder="professor@example.com"></label><div id="form-error"></div><div class="modal-actions"><button class="btn subtle" type="button" data-close>Cancel</button><button class="btn primary">Add professor</button></div></form>');
    m.querySelector('form').onsubmit = async function (event) { event.preventDefault(); try { await Auth.api('/api/admin/professors', { method: 'POST', body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); closeModal(); done(); } catch (reason) { m.querySelector('#form-error').innerHTML = error(reason.message); } };
  }
  function openCourseModal(done) {
    var m = modal('<div class="control-eyebrow">Course builder</div><h2>Add a source-backed class</h2><p class="modal-sub">Upload the protected source PDFs first. StudyMAF keeps them private, creates a draft course, and queues it for lesson, diagram, and tutor-context authoring.</p><form class="account-form source-course-form" id="course-form"><div class="course-form-grid"><label>Course code<input name="code" required placeholder="CALC1"></label><label>Subject<input name="subject" required placeholder="calculus"></label></div><label>Course title<input name="title" required placeholder="Calculus I"></label><label>Description<textarea name="description" placeholder="What students will learn in this course"></textarea></label><section class="source-upload"><div><strong>Syllabus PDF</strong><small>Required. It determines the required lessons and assignments.</small></div><input name="syllabus" type="file" accept="application/pdf,.pdf" required></section><section class="source-upload"><div><strong>Textbook PDFs</strong><small>Required. These are stored privately and later broken into small tutor-reference sections.</small></div><input name="textbooks" type="file" accept="application/pdf,.pdf" multiple required></section><p class="source-upload-note">PDF only · 50 MB maximum per file on the current plan · uploaded source material is never public.</p><div id="course-progress" class="course-progress" aria-live="polite"></div><div id="form-error"></div><div class="modal-actions"><button class="btn subtle" type="button" data-close>Cancel</button><button class="btn primary" type="submit">Create class and upload sources</button></div></form>', { wide: true });
    m.querySelector('form').onsubmit = async function (event) { event.preventDefault(); var form = event.currentTarget, syllabus = form.elements.syllabus.files[0], textbooks = Array.prototype.slice.call(form.elements.textbooks.files || []), submit = form.querySelector('[type="submit"]'), progress = m.querySelector('#course-progress'), failure = m.querySelector('#form-error'); if (!syllabus || !textbooks.length) { failure.innerHTML = error('Add one syllabus PDF and at least one textbook PDF.'); return; } submit.disabled = true; failure.innerHTML = ''; function note(message) { progress.textContent = message; } try { note('Creating a private draft course…'); var created = await Auth.api('/api/admin/courses', { method: 'POST', body: JSON.stringify({ code: form.elements.code.value, title: form.elements.title.value, subject: form.elements.subject.value, description: form.elements.description.value, source_upload: true }) }), course = created.course, sources = [{ kind: 'syllabus', file: syllabus }].concat(textbooks.map(function (file) { return { kind: 'textbook', file: file }; })); for (var index = 0; index < sources.length; index++) { var source = sources[index]; note('Uploading ' + (index + 1) + ' of ' + sources.length + ': ' + source.file.name); var stored = await Auth.uploadCourseSource(course.id, source.kind, source.file); await Auth.api('/api/admin/courses', { method: 'PATCH', body: JSON.stringify(Object.assign({ action: 'attach_document', id: course.id, kind: source.kind }, stored)) }); } note('Queueing the course builder…'); await Auth.api('/api/admin/courses', { method: 'PATCH', body: JSON.stringify({ action: 'queue_ingestion', id: course.id }) }); closeModal(); done(); } catch (reason) { submit.disabled = false; failure.innerHTML = error(reason.message); } };
  }
  function openSourceUploadModal(course, done) {
    if (!course || !course.id) return;
    var m = modal('<div class="control-eyebrow">Private source files</div><h2>Attach files to ' + esc(course.code || 'this course') + '</h2><p class="modal-sub">These PDFs stay in StudyMAF’s private course library. Students and professors receive a short-lived download only for a class they can access.</p><form class="account-form source-course-form" id="source-files-form"><section class="source-upload"><div><strong>Syllabus PDF</strong><small>Add or replace the syllabus for this published course.</small></div><input name="syllabus" type="file" accept="application/pdf,.pdf"></section><section class="source-upload"><div><strong>Textbook PDFs</strong><small>You may select one or more textbook files.</small></div><input name="textbooks" type="file" accept="application/pdf,.pdf" multiple></section><p class="source-upload-note">PDF only · 50 MB maximum per file on the current plan. Compress, split, or store larger licensed PDFs externally before attaching them.</p><div id="source-progress" class="course-progress" aria-live="polite"></div><div id="source-error"></div><div class="modal-actions"><button class="btn subtle" type="button" data-close>Cancel</button><button class="btn primary" type="submit">Save private source files</button></div></form>', { wide: true });
    m.querySelector('form').onsubmit = async function (event) {
      event.preventDefault(); var form = event.currentTarget, syllabus = form.elements.syllabus.files[0], textbooks = Array.prototype.slice.call(form.elements.textbooks.files || []), sources = (syllabus ? [{ kind: 'syllabus', file: syllabus }] : []).concat(textbooks.map(function (file) { return { kind: 'textbook', file: file }; })), submit = form.querySelector('[type="submit"]'), progress = m.querySelector('#source-progress'), failure = m.querySelector('#source-error');
      if (!sources.length) { failure.innerHTML = error('Choose at least one syllabus or textbook PDF.'); return; }
      submit.disabled = true; failure.innerHTML = '';
      try { for (var index = 0; index < sources.length; index++) { var source = sources[index]; progress.textContent = 'Uploading ' + (index + 1) + ' of ' + sources.length + ': ' + source.file.name; var stored = await Auth.uploadCourseSource(course.id, source.kind, source.file); await Auth.api('/api/admin/courses', { method: 'PATCH', body: JSON.stringify(Object.assign({ action: 'attach_document', id: course.id, kind: source.kind }, stored)) }); } progress.textContent = 'Private source files saved.'; setTimeout(function () { closeModal(); done(); }, 400); }
      catch (reason) { submit.disabled = false; failure.innerHTML = error(reason.message); }
    };
  }
  function roster(classId) {
    var m = modal('<h2>Student list</h2><div id="roster" class="account-empty">Loading student list…</div>'), host = m.querySelector('#roster');
    async function load() { try { var data = await Auth.api('/api/professor/students?class_id=' + encodeURIComponent(classId)); host.className = ''; host.innerHTML = '<form class="account-form" id="student-form"><label>Student email<input name="student_email" type="email" required placeholder="student@example.com"></label><div id="student-error"></div><button class="btn primary">Add student</button></form><div class="roster-list">' + ((data.students || []).map(function (student) { return '<div><span class="person-mark">' + initials((student.profiles || {}).display_name || student.student_email) + '</span><p><strong>' + esc((student.profiles || {}).display_name || student.student_email) + '</strong><small>' + esc(student.student_email) + ' · ' + esc(student.status) + '</small></p><button class="btn danger small" type="button" data-remove-student="' + esc(student.student_email) + '">Remove</button></div>'; }).join('') || '<div class="empty-state">No students yet.</div>') + '</div>'; host.querySelector('form').onsubmit = async function (event) { event.preventDefault(); try { await Auth.api('/api/professor/students', { method: 'POST', body: JSON.stringify({ class_id: classId, student_email: new FormData(event.currentTarget).get('student_email') }) }); load(); } catch (reason) { host.querySelector('#student-error').innerHTML = error(reason.message); } }; host.querySelectorAll('[data-remove-student]').forEach(function (button) { button.onclick = async function () { if (!window.confirm('Remove ' + button.dataset.removeStudent + ' from this class?')) return; button.disabled = true; try { await Auth.api('/api/professor/students', { method: 'DELETE', body: JSON.stringify({ class_id: classId, student_email: button.dataset.removeStudent }) }); load(); } catch (reason) { button.disabled = false; host.querySelector('#student-error').innerHTML = error(reason.message); } }; }); } catch (reason) { host.innerHTML = error(reason.message); } }
    load();
  }
  function workspace(target, title, subtitle) { target.innerHTML = '<div class="page wrap account-fallback"><div class="section-head"><div><h1>' + esc(title) + '</h1><p class="section-sub">' + esc(subtitle) + '</p></div></div><div id="account-body" class="account-body"><div class="account-empty">Loading…</div></div></div>'; return target.querySelector('#account-body'); }
  async function renderProfessor(target) {
    if (!account() || account().role !== 'professor') { target.innerHTML = '<div class="page wrap"><div class="account-empty">This area is available to professor accounts.</div></div>'; return; }
    target.innerHTML = '<div class="page wrap"><div id="account-body" class="account-body"><div class="account-empty">Loading…</div></div></div>';
    var body = target.querySelector('#account-body');
    try {
      var loaded = await Promise.all([Auth.api('/api/catalog'), Auth.api('/api/professor/classes'), fetch(new URL('../data/classes.json', import.meta.url)).then(function (r) { return r.ok ? r.json() : { classes: [] }; }).catch(function () { return { classes: [] }; })]), catalog = loaded[0].courses || [], classes = loaded[1].classes || [], lessonCounts = {};
      (loaded[2].classes || []).forEach(function (item) { lessonCounts[String(item.code || '').toUpperCase()] = (item.lessons || []).length; });
      function lessonCountFor(course) { return lessonCounts[String(course.code || '').toUpperCase()] || (Array.isArray(course.lessons) ? course.lessons.length : 0); }
      var showAllClasses = false;
      function openCreateClass() {
        if (!catalog.length) return;
        var m = modal('<div class="control-eyebrow">New class</div><h2>Create a class</h2><p class="modal-sub">Choose a course and name your section. You add students by email afterward.</p><form class="account-form" id="create-class-form"><label>Course<select name="course_id" required><option value="">Choose a course</option>' + catalog.map(function (course) { return '<option value="' + esc(course.id) + '">' + esc(course.code || 'Course') + ' — ' + esc(course.title || 'Untitled course') + '</option>'; }).join('') + '</select></label><label>Section name<input name="section_label" placeholder="Section 01" required></label><label>Term<input name="term" placeholder="Fall 2026"></label><div id="create-class-error"></div><div class="modal-actions"><button class="btn subtle" type="button" data-close>Cancel</button><button class="btn primary" type="submit">Create class</button></div></form>');
        m.querySelector('form').onsubmit = async function (event) { event.preventDefault(); var submit = event.currentTarget.querySelector('[type="submit"]'); submit.disabled = true; try { var saved = await Auth.api('/api/professor/classes', { method: 'POST', body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); saved.class.course_catalog = catalog.filter(function (course) { return course.id === saved.class.course_id; })[0]; classes.unshift(saved.class); closeModal(); draw(); } catch (reason) { submit.disabled = false; m.querySelector('#create-class-error').innerHTML = error(reason.message); } };
      }
      function draw() {
        function classCard(item) { var course = item.course_catalog || {}; return '<article class="prof-card"><div class="prof-card-head"><span class="role-pill">' + esc(course.subject || 'Course') + '</span><span class="prof-card-tag">' + (item.term ? esc(item.term) : 'No term') + '</span></div><h3>' + esc(course.code || 'Course') + (item.section_label ? ' · ' + esc(item.section_label) : '') + '</h3><p class="prof-card-title">' + esc(course.title || 'Untitled course') + '</p><div class="prof-card-actions"><button class="btn ghost small" data-roster="' + esc(item.id) + '">Students</button><button class="btn primary small" data-review="' + esc(item.id) + '">Open class</button></div></article>'; }
        function libraryCard(course) { return '<article class="prof-card prof-card--lib"><div class="prof-card-head"><span class="role-pill">' + esc(course.subject || 'Course') + '</span><span class="prof-card-tag">' + lessonCountFor(course) + ' lessons</span></div><h3>' + esc(course.code || 'Course') + '</h3><p class="prof-card-title">' + esc(course.title || 'Untitled course') + '</p><div class="prof-card-actions"><button class="btn ghost small wide" data-catalog-review="' + esc(course.id) + '">Preview course</button></div></article>'; }
        var limit = 6, visibleClasses = showAllClasses ? classes : classes.slice(0, limit);
        var classesHtml = classes.length ? visibleClasses.map(classCard).join('') : '<div class="empty-state prof-empty">You have no classes yet. Click <strong>+ New class</strong> to create your first section, then add students by email.</div>';
        var moreHtml = classes.length > limit ? '<button class="btn ghost small professor-show-more" type="button" id="toggle-classes">' + (showAllClasses ? 'Show less' : 'Show all ' + classes.length + ' classes') + '</button>' : '';
        body.innerHTML = '<div class="professor-shell"><div class="control-hero prof-hero"><div><div class="control-eyebrow">Teaching workspace</div><h1>Your classes</h1><p>Manage rosters, preview any published course, and open a class to review student progress.</p></div><div class="control-actions"><button class="btn primary" id="new-class"' + (catalog.length ? '' : ' disabled') + '>+ New class</button></div></div>'
          + '<section class="control-section"><div class="section-row"><div><span class="control-eyebrow">Classes you teach</span><h2>Your sections</h2><p>Open a class to review its lessons and student progress, or manage the roster.</p></div><span class="panel-chip">' + classes.length + ' class' + (classes.length === 1 ? '' : 'es') + '</span></div><div class="prof-grid">' + classesHtml + '</div>' + moreHtml + '</section>'
          + '<section class="control-section"><div class="section-row"><div><span class="control-eyebrow">Course library</span><h2>Preview any course</h2><p>Explore the lessons, Learn checks, Practice, and Test Mode without creating a section.</p></div><span class="panel-chip">' + catalog.length + ' course' + (catalog.length === 1 ? '' : 's') + '</span></div><div class="prof-grid">' + (catalog.map(libraryCard).join('') || '<div class="empty-state">No published courses are available yet.</div>') + '</div></section></div>';
        var newBtn = body.querySelector('#new-class'); if (newBtn) newBtn.onclick = openCreateClass;
        body.querySelectorAll('[data-roster]').forEach(function (button) { button.onclick = function () { roster(button.dataset.roster); }; });
        body.querySelectorAll('[data-review]').forEach(function (button) { button.onclick = function () { reviewClass(button.dataset.review); }; });
        body.querySelectorAll('[data-catalog-review]').forEach(function (button) { button.onclick = function () { var course = catalog.filter(function (item) { return item.id === button.dataset.catalogReview; })[0]; if (course) reviewClass('', course); }; });
        var toggleBtn = body.querySelector('#toggle-classes'); if (toggleBtn) toggleBtn.onclick = function () { showAllClasses = !showAllClasses; draw(); };
      }
      draw();
    } catch (reason) { body.innerHTML = error(reason.message); }
  }
  async function renderAdmin(target) {
    if (!account() || account().role !== 'admin') { target.innerHTML = '<div class="page wrap"><div class="account-empty">This area is only for StudyMAF administrators.</div></div>'; return; }
    target.innerHTML = '<div class="control-workspace"><aside class="control-nav"><div class="nav-mark">Σ</div><button class="active" data-view="overview">Overview</button><button data-view="people">People</button><button data-view="classes">Classes</button><button data-view="analytics">Analytics</button><div class="nav-bottom">Protected administrator workspace.<br>Student data stays server-side.</div></aside><main class="control-main" id="control-main"><div class="account-empty">Loading Control…</div></main></div>';
    try {
      var data = await Auth.api('/api/admin/dashboard'), users = data.users || [], courses = data.courses || [], classes = data.classes || [], enrollments = data.enrollments || [], roles = Object.fromEntries((data.roles || []).map(function (item) { return [item.user_id, item.role]; })), metrics = data.analytics && data.analytics.users || {}, main = target.querySelector('#control-main'), view = 'overview', analyticsRange = 'week', selectedStudent = '';
      function classCount(id) { return enrollments.filter(function (entry) { return entry.class_section_id === id && entry.status !== 'removed'; }).length; }
      function total(metric) { return users.reduce(function (sum, user) { return sum + n((metrics[user.id] || {})[metric]); }, 0); }
      function modeSeconds(key) { return users.reduce(function (sum, user) { return sum + n(((metrics[user.id] || {}).modes || {})[key]); }, 0); }
      function modeVisual() { var items = [{ key: 'learn', name: 'Learn', color: 'orange', icon: '◌' }, { key: 'practice', name: 'Practice', color: 'violet', icon: '✦' }, { key: 'test', name: 'Test', color: 'blue', icon: '✓' }], amount = items.map(function (item) { return modeSeconds(item.key); }), overall = amount.reduce(function (sum, value) { return sum + value; }, 0) || 1; return '<div class="mode-visual">' + items.map(function (item, index) { var value = amount[index], share = Math.round(value / overall * 100); return '<div class="mode-row ' + item.color + '"><span class="mode-icon">' + item.icon + '</span><div class="mode-copy"><div><strong>' + item.name + '</strong><b>' + time(value) + '</b></div><span class="mode-track"><i style="width:' + share + '%"></i></span><small>' + share + '% of recorded study time</small></div></div>'; }).join('') + '</div>'; }
      function activityVisual() { return '<div class="class-activity-list">' + (classes.slice(0, 6).map(function (section) { var course = section.course_catalog || {}; return '<button class="class-activity-card" data-review="' + esc(section.id) + '"><span class="activity-course-mark">' + esc(String(course.code || 'CL').slice(0, 4)) + '</span><span class="activity-class-copy"><strong>' + esc(courseLabel(course) || section.section_label) + '</strong><small>' + esc(section.section_label) + (section.term ? ' · ' + esc(section.term) : '') + '</small></span><span class="activity-students"><b>' + classCount(section.id) + '</b><small>students</small></span><span class="activity-arrow">→</span></button>'; }).join('') || '<div class="empty-state">No classes yet.</div>') + '</div>'; }
      function blankAnalyticsRow(at) { return { at: at.toISOString(), study_seconds: 0, calculator_uses: 0, modes: { learn: 0, practice: 0, test: 0, study: 0 }, delivery: { online: 0, offline: 0 } }; }
      function addAnalyticsRow(target, source) { target.study_seconds += n(source.study_seconds); target.calculator_uses += n(source.calculator_uses); ['learn', 'practice', 'test', 'study'].forEach(function (mode) { target.modes[mode] += n((source.modes || {})[mode]); }); ['online', 'offline'].forEach(function (mode) { target.delivery[mode] += n((source.delivery || {})[mode]); }); }
      function dayStart(value) { var date = new Date(value); return new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate())); }
      function rangeRows(range) {
        var generated = new Date(data.analytics && data.analytics.generated_at || Date.now()), hourly = data.analytics && data.analytics.hourly || [], daily = data.analytics && data.analytics.daily || [], slots = [], map = {}, start, end, unit;
        function key(date) { return unit === 'hour' ? date.toISOString().slice(0, 13) : unit === 'day' ? date.toISOString().slice(0, 10) : date.getUTCFullYear() + '-' + date.getUTCMonth(); }
        function addSlot(date) { var row = blankAnalyticsRow(date); map[key(date)] = row; slots.push(row); }
        if (range === 'day') { unit = 'hour'; start = new Date(Date.UTC(generated.getUTCFullYear(), generated.getUTCMonth(), generated.getUTCDate(), generated.getUTCHours() - 23)); end = new Date(Date.UTC(generated.getUTCFullYear(), generated.getUTCMonth(), generated.getUTCDate(), generated.getUTCHours())); for (var hour = new Date(start); hour <= end; hour.setUTCHours(hour.getUTCHours() + 1)) addSlot(new Date(hour)); hourly.forEach(function (item) { var date = new Date(item.at), row = map[key(date)]; if (row) addAnalyticsRow(row, item); }); return slots; }
        unit = range === 'week' || range === 'month' ? 'day' : 'month';
        if (range === 'week') { end = dayStart(generated); start = new Date(end); start.setUTCDate(start.getUTCDate() - 6); for (var weekDay = new Date(start); weekDay <= end; weekDay.setUTCDate(weekDay.getUTCDate() + 1)) addSlot(new Date(weekDay)); }
        else if (range === 'month') { start = new Date(Date.UTC(generated.getUTCFullYear(), generated.getUTCMonth(), 1)); end = new Date(Date.UTC(generated.getUTCFullYear(), generated.getUTCMonth() + 1, 0)); for (var monthDay = new Date(start); monthDay <= end; monthDay.setUTCDate(monthDay.getUTCDate() + 1)) addSlot(new Date(monthDay)); }
        else { var first = daily.length ? dayStart(daily[0].at) : dayStart(generated), lastMonth = range === 'year' ? new Date(Date.UTC(generated.getUTCFullYear(), 11, 1)) : new Date(Date.UTC(generated.getUTCFullYear(), generated.getUTCMonth(), 1)); start = range === 'year' ? new Date(Date.UTC(generated.getUTCFullYear(), 0, 1)) : new Date(Date.UTC(first.getUTCFullYear(), first.getUTCMonth(), 1)); end = new Date(Date.UTC(lastMonth.getUTCFullYear(), lastMonth.getUTCMonth() + 1, 0)); for (var month = new Date(start); month <= lastMonth; month.setUTCMonth(month.getUTCMonth() + 1)) addSlot(new Date(month)); }
        daily.forEach(function (item) { var date = dayStart(item.at); if (date < start || date > end) return; var row = map[key(date)]; if (row) addAnalyticsRow(row, item); }); return slots;
      }
      function chartLabel(at, range) { var date = new Date(at); return range === 'day' ? date.toLocaleTimeString([], { hour: 'numeric' }) : range === 'year' ? date.toLocaleDateString([], { month: 'short' }) : range === 'all' ? date.toLocaleDateString([], { month: 'short', year: '2-digit' }) : date.toLocaleDateString([], { month: 'short', day: 'numeric' }); }
      function lineChart(rows, key, title, unit) { var values = rows.map(function (row) { return key === 'study_seconds' ? n(row[key]) / 60 : n(row[key]); }), max = Math.max.apply(Math, values.concat([1])), width = 640, height = 224, left = 48, right = 16, top = 18, bottom = 34, plotW = width - left - right, plotH = height - top - bottom, points = values.map(function (value, index) { return (left + (values.length < 2 ? 0 : index / (values.length - 1) * plotW)).toFixed(1) + ',' + (top + plotH - value / max * plotH).toFixed(1); }).join(' '), area = left + ',' + (top + plotH) + ' ' + points + ' ' + (width - right) + ',' + (top + plotH), ticks = [0, Math.floor((values.length - 1) / 2), values.length - 1].filter(function (value, index, list) { return list.indexOf(value) === index; }); return '<section class="trend-card"><div class="trend-heading"><div><h2>' + esc(title) + '</h2><p>' + esc(unit) + '</p></div><strong>' + (key === 'study_seconds' ? time(values.reduce(function (sum, value) { return sum + value * 60; }, 0)) : values.reduce(function (sum, value) { return sum + value; }, 0)) + '</strong></div><svg class="trend-svg" viewBox="0 0 ' + width + ' ' + height + '" role="img" aria-label="' + esc(title) + ' over time"><line class="trend-grid" x1="' + left + '" y1="' + top + '" x2="' + (width - right) + '" y2="' + top + '"/><line class="trend-grid" x1="' + left + '" y1="' + (top + plotH / 2) + '" x2="' + (width - right) + '" y2="' + (top + plotH / 2) + '"/><line class="trend-grid" x1="' + left + '" y1="' + (top + plotH) + '" x2="' + (width - right) + '" y2="' + (top + plotH) + '"/><text x="4" y="' + (top + 4) + '">' + Math.round(max) + '</text><text x="4" y="' + (top + plotH) + '">0</text><polygon class="trend-area" points="' + area + '"/><polyline class="trend-line" points="' + points + '"/>' + ticks.map(function (index) { return '<text x="' + (left + (values.length < 2 ? 0 : index / (values.length - 1) * plotW)) + '" y="' + (height - 9) + '" text-anchor="middle">' + esc(chartLabel(rows[index].at, analyticsRange)) + '</text>'; }).join('') + '</svg></section>'; }
      function allocation(rows) { var totals = { learn: 0, practice: 0, test: 0, online: 0, offline: 0 }; rows.forEach(function (row) { ['learn', 'practice', 'test'].forEach(function (key) { totals[key] += n(row.modes[key]); }); ['online', 'offline'].forEach(function (key) { totals[key] += n(row.delivery[key]); }); }); var studied = totals.learn + totals.practice + totals.test || 1, delivery = totals.online + totals.offline || 1; function bar(label, value, max, tint) { return '<div class="allocation-row"><div><strong>' + label + '</strong><span>' + time(value) + '</span></div><i class="' + tint + '" style="width:' + Math.round(value / max * 100) + '%"></i></div>'; } return '<section class="allocation-card"><div class="trend-heading"><div><h2>Learning mix</h2><p>Time spent by mode and delivery</p></div></div>' + bar('Learn', totals.learn, studied, 'orange') + bar('Practice', totals.practice, studied, 'violet') + bar('Test', totals.test, studied, 'blue') + '<div class="allocation-divider"></div>' + bar('Online', totals.online, delivery, 'green') + bar('Offline', totals.offline, delivery, 'slate') + '</section>'; }
      function visualOverview() { return hero() + '<div class="control-metrics">' + metricCard(users.length, 'Verified accounts', 'orange') + metricCard(time(total('total_time_seconds')), 'Active study time', 'violet') + metricCard(classes.length, 'Professor classes', 'green') + metricCard((data.professor_invites || []).length, 'Pending professors', 'blue') + '</div><div class="control-layout"><section class="control-panel"><div class="panel-head"><div><h2>Recent class activity</h2><p>Open a class to review published lessons and student progress.</p></div><span class="panel-chip">Live roster</span></div>' + activityVisual() + '</section><section class="control-panel"><div class="panel-head"><div><h2>Learning modes</h2><p>Clear time breakdown across all active accounts.</p></div></div>' + modeVisual() + '</section></div>'; }
      function hero() { return '<div class="control-hero"><div><div class="control-eyebrow">Administrator workspace</div><h1>StudyMAF Control</h1><p>Open any class to inspect its published content and the learning progress of students who are enrolled.</p></div><div class="control-actions"><button class="btn primary" id="add-professor">+ Add professor</button><button class="btn ghost" id="add-course">Add class</button><button class="btn ghost" id="refresh">Refresh</button></div></div>'; }
      function removeAccount(user) { var m = modal('<div class="control-eyebrow">Remove account</div><h2>Remove ' + esc(profileName(user)) + '?</h2><p class="modal-sub">This permanently removes their sign-in, progress, and recorded learning activity. It cannot be undone.</p><div class="modal-actions"><button class="btn subtle" data-close>Cancel</button><button class="btn danger" id="confirm-account-remove">Remove account</button></div>'); m.querySelector('#confirm-account-remove').onclick = async function () { var button = m.querySelector('#confirm-account-remove'); button.disabled = true; try { await Auth.api('/api/admin/dashboard', { method: 'DELETE', body: JSON.stringify({ user_id: user.id }) }); closeModal(); renderAdmin(target); } catch (reason) { button.disabled = false; m.insertAdjacentHTML('beforeend', error(reason.message)); } }; }
      function userRow(user) { var metric = metrics[user.id] || {}, canRemove = account() && account().user.id !== user.id; return '<tr><td><div class="person"><span class="person-mark">' + initials(profileName(user)) + '</span><span><strong>' + esc(profileName(user)) + '</strong><small>' + esc(user.email) + '</small></span></div></td><td><span class="role-pill">' + esc(roles[user.id] || 'student') + '</span></td><td>' + time(metric.total_time_seconds) + '</td><td>' + progressLine(metric.overall_completion_percent) + '</td><td><div class="table-actions"><button class="btn ghost small" data-user="' + esc(user.id) + '">Open</button>' + (canRemove ? '<button class="btn danger small" data-remove="' + esc(user.id) + '">Remove</button>' : '') + '</div></td></tr>'; }
      function userReport(user) { var metric = metrics[user.id] || {}; modal('<div class="control-eyebrow">Account learning data</div><h2>' + esc(profileName(user)) + '</h2><p class="modal-sub">' + esc(user.email) + '</p><div class="account-grid">' + metricCard(time(metric.total_time_seconds), 'Active study time', 'green') + metricCard(metric.overall_completion_percent == null ? '—' : pct(metric.overall_completion_percent) + '%', 'Completion', 'orange') + metricCard(metric.calculator_uses || 0, 'Calculator use', 'blue') + '</div><section class="review-lesson-list">' + ((metric.classes || []).map(function (item) { return '<div class="review-lesson"><div><strong>' + esc(item.label) + '</strong><small>' + time(item.total_time_seconds) + ' active study</small></div>' + progressLine(item.completion_percent) + '</div>'; }).join('') || '<div class="empty-state">No learning activity recorded yet.</div>') + '</section><div class="modal-actions"><button class="btn primary" data-close>Done</button></div>', { wide: true }); }
      function overview() { return hero() + '<div class="control-metrics">' + metricCard(users.length, 'Verified accounts', 'orange') + metricCard(time(total('total_time_seconds')), 'Active study time', 'violet') + metricCard(classes.length, 'Professor classes', 'green') + metricCard((data.professor_invites || []).length, 'Pending professors', 'blue') + '</div><div class="control-layout"><section class="control-panel"><div class="panel-head"><div><h2>Recent class activity</h2><p>Class sections and enrollment at a glance.</p></div></div><div class="review-stat-list">' + (classes.slice(0, 6).map(function (section) { var course = section.course_catalog || {}; return '<button data-review="' + esc(section.id) + '"><span>' + esc(course.code || '') + ' · ' + esc(section.section_label) + '</span><b>' + classCount(section.id) + ' students</b></button>'; }).join('') || '<span>No classes yet.</span>') + '</div></section><section class="control-panel"><div class="panel-head"><div><h2>Learning modes</h2><p>Across all active accounts.</p></div></div><div class="review-stat-list"><span><b>' + time(users.reduce(function (sum, user) { return sum + n(((metrics[user.id] || {}).modes || {}).learn); }, 0)) + '</b> Learn</span><span><b>' + time(users.reduce(function (sum, user) { return sum + n(((metrics[user.id] || {}).modes || {}).practice); }, 0)) + '</b> Practice</span><span><b>' + time(users.reduce(function (sum, user) { return sum + n(((metrics[user.id] || {}).modes || {}).test); }, 0)) + '</b> Test</span></div></section></div>'; }
      function people() { var students = users.filter(function (user) { return (roles[user.id] || 'student') === 'student'; }), team = users.filter(function (user) { return (roles[user.id] || 'student') !== 'student'; }); function table(rows, empty) { return '<div class="data-table-wrap"><table class="control-table"><thead><tr><th>Account</th><th>Role</th><th>Time</th><th>Completion</th><th></th></tr></thead><tbody>' + (rows.map(userRow).join('') || '<tr><td colspan="5">' + esc(empty) + '</td></tr>') + '</tbody></table></div>'; } return hero() + '<section class="control-section people-section"><div class="section-row"><div><span class="control-eyebrow">Students</span><h2>Student accounts</h2><p>Learning records stay separate from teaching and administrative access.</p></div><span class="panel-chip">' + students.length + ' students</span></div>' + table(students, 'No student accounts yet.') + '</section><section class="control-section people-section"><div class="section-row"><div><span class="control-eyebrow">Team access</span><h2>Professors and administrators</h2><p>People who can manage class content, rosters, or StudyMAF Control.</p></div><span class="panel-chip">' + team.length + ' team members</span></div>' + table(team, 'No professor or administrator accounts yet.') + '</section>'; }
      function classesView() { function courseCard(course) { course = course || {}; var jobs = Array.isArray(course.course_ingestion_jobs) ? course.course_ingestion_jobs.slice().sort(function (a, b) { return String((b || {}).requested_at || '').localeCompare(String((a || {}).requested_at || '')); }) : [], job = jobs[0] || {}, status = String(job.status || (course.is_active ? 'published' : 'draft')); return '<article class="control-class-card source-card"><div class="class-card-top"><span class="course-code-mark course-code-full">' + esc(course.code || 'COURSE') + '</span><span class="role-pill">' + esc(status.replace(/_/g, ' ')) + '</span></div><div class="class-card-copy"><h3>' + esc(course.title || 'Untitled course') + '</h3><p>' + esc(course.subject || 'Course') + '</p></div><div class="class-card-footer"><button class="btn primary small" data-course-review="' + esc(course.id || '') + '">View class <span aria-hidden="true">→</span></button></div></article>'; } function sectionCard(section) { section = section || {}; var course = section.course_catalog || {}, professor = section.profiles || {}; return '<article class="control-class-card"><div class="class-card-top"><span class="course-code-mark course-code-full">' + esc(course.code || 'COURSE') + '</span><span class="role-pill">' + esc(course.subject || 'Course') + '</span></div><div class="class-card-copy"><h3>' + esc(course.title || 'Untitled course') + '</h3><p>' + esc(section.section_label) + (section.term ? ' · ' + esc(section.term) : '') + '</p><small>Professor · ' + esc(professor.display_name || professor.email || 'Not assigned') + '</small></div><div class="class-card-footer"><span><b>' + classCount(section.id) + '</b> student' + (classCount(section.id) === 1 ? '' : 's') + '</span><button class="btn primary small" data-review="' + esc(section.id) + '">Open class <span aria-hidden="true">→</span></button></div></article>'; } return hero() + '<section class="control-section"><div class="section-row"><div><span class="control-eyebrow">Course library</span><h2>Course builds</h2><p>Private source PDFs and their publication state. Open any course to preview its student-facing lessons and download the files only when needed.</p></div><span class="panel-chip">' + courses.length + ' courses</span></div><div class="class-card-list admin-classes">' + (courses.map(courseCard).join('') || '<div class="empty-state">No course templates exist yet.</div>') + '</div></section><section class="control-section classes-section"><div class="section-row"><div><span class="control-eyebrow">Published sections</span><h2>Professor classes</h2><p>Open a class to review the student-facing lessons, roster, and learning activity.</p></div><span class="panel-chip">' + classes.length + ' classes</span></div><div class="class-card-list admin-classes">' + (classes.map(sectionCard).join('') || '<div class="empty-state">No professor classes exist yet.</div>') + '</div></section>'; }
      function analytics() { var rows = rangeRows(analyticsRange), students = users.filter(function (user) { return (roles[user.id] || 'student') === 'student'; }), selected = users.filter(function (user) { return user.id === selectedStudent; })[0]; return hero() + '<section class="analytics-toolbar"><div><span class="control-eyebrow">Live analytics</span><h2>Activity over time</h2><p>Calendar periods expand as StudyMAF grows. <strong>All</strong> shows every recorded month from the first activity onward.</p></div><div class="range-toggle" role="group" aria-label="Analytics time range">' + ['day', 'week', 'month', 'year', 'all'].map(function (range) { return '<button class="' + (analyticsRange === range ? 'active' : '') + '" data-range="' + range + '">' + range.charAt(0).toUpperCase() + range.slice(1) + '</button>'; }).join('') + '</div></section><div class="trend-grid-layout">' + lineChart(rows, 'study_seconds', 'Active study time', 'Minutes recorded in the selected period') + lineChart(rows, 'calculator_uses', 'Calculator use', 'Recorded uses in the selected period') + '</div><div class="analytics-split">' + allocation(rows) + '<section class="account-explorer"><div><h2>Per-student analytics</h2><p>Select a student instead of scanning a long list of accounts.</p></div><label>Student account<select id="analytics-student"><option value="">Choose a student</option>' + students.map(function (user) { return '<option value="' + esc(user.id) + '"' + (user.id === selectedStudent ? ' selected' : '') + '>' + esc(profileName(user)) + '</option>'; }).join('') + '</select></label><button class="btn primary" id="open-selected-student"' + (selected ? '' : ' disabled') + '>Open student data</button>' + (selected ? '<div class="selected-student-summary"><strong>' + esc(profileName(selected)) + '</strong><span>' + time((metrics[selected.id] || {}).total_time_seconds) + ' active study · ' + pct((metrics[selected.id] || {}).overall_completion_percent) + '% completion</span></div>' : '') + '</section></div>'; }
      function bind() { main.querySelectorAll('[data-review]').forEach(function (button) { button.onclick = function () { reviewClass(button.dataset.review); }; }); main.querySelectorAll('[data-course-review]').forEach(function (button) { button.onclick = function () { var course = courses.filter(function (item) { return item.id === button.dataset.courseReview; })[0]; if (course) reviewClass('', course); }; }); main.querySelectorAll('[data-source-upload]').forEach(function (button) { button.onclick = function () { var course = courses.filter(function (item) { return item.id === button.dataset.sourceUpload; })[0]; if (course) openSourceUploadModal(course, function () { renderAdmin(target); }); }; }); main.querySelectorAll('[data-user]').forEach(function (button) { button.onclick = function () { userReport(users.filter(function (user) { return user.id === button.dataset.user; })[0]); }; }); main.querySelectorAll('[data-remove]').forEach(function (button) { button.onclick = function () { var user = users.filter(function (item) { return item.id === button.dataset.remove; })[0]; if (user) removeAccount(user); }; }); main.querySelectorAll('[data-range]').forEach(function (button) { button.onclick = function () { analyticsRange = button.dataset.range; draw(); }; }); var studentSelect = main.querySelector('#analytics-student'), selectedButton = main.querySelector('#open-selected-student'); if (studentSelect) studentSelect.onchange = function () { selectedStudent = studentSelect.value; draw(); }; if (selectedButton) selectedButton.onclick = function () { var user = users.filter(function (item) { return user.id === selectedStudent; })[0]; if (user) userReport(user); }; var refresh = main.querySelector('#refresh'); if (refresh) refresh.onclick = function () { renderAdmin(target); }; var professor = main.querySelector('#add-professor'); if (professor) professor.onclick = function () { openProfessorModal(function () { renderAdmin(target); }); }; var course = main.querySelector('#add-course'); if (course) course.onclick = function () { openCourseModal(function () { renderAdmin(target); }); }; }
      function draw() { try { main.innerHTML = view === 'people' ? people() : view === 'classes' ? classesView() : view === 'analytics' ? analytics() : visualOverview(); bind(); target.querySelectorAll('[data-view]').forEach(function (button) { button.classList.toggle('active', button.dataset.view === view); }); } catch (reason) { main.innerHTML = '<div class="account-empty">' + error('This Control section could not load. Please refresh and try again.') + '</div>'; } clearTimeout(window.StudyMAFControlRefresh); window.StudyMAFControlRefresh = setTimeout(function () { renderAdmin(target); }, 3600000); }
      target.onclick = function (event) { var button = event.target.closest('[data-view]'); if (!button || !target.contains(button)) return; event.preventDefault(); var next = button.dataset.view; if (['overview', 'people', 'classes', 'analytics'].indexOf(next) < 0 || next === view) return; view = next; draw(); };
      draw();
    } catch (reason) { target.querySelector('#control-main').innerHTML = error(reason.message); }
  }
  return { ready: function () { return Auth.init(); }, mountHeader: function () { var nav = document.querySelector('.header-actions'); if (!nav) return; header = document.createElement('button'); header.className = 'btn ghost account-header-name'; header.type = 'button'; header.onclick = openAccount; nav.appendChild(header); syncHeader(); Auth.onChange(syncHeader); }, openSignIn: function () { location.assign(rootUrl('signin/')); }, renderProfessor: renderProfessor, renderAdmin: renderAdmin, account: account, openAccount: openAccount };
}
